language: python
python:
- '2.7'
install:
- python setup.py develop
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  password:
    secure: UIae5OU10iMM3IjFv4qjuxRGDM+KpiJBPg0JV5z3nf6gteQDnQOitZgC7ODRW0easvrUvu6W/SPWKp7/wj0NXM7vM6lFlTXGKMjFVzN/bDHtoXDCwdDYBetiE19WdSsUH4vvXgY4Em3R2OeMG4uLAOOEoWXYZrxVSGwJvgF2TWNk7vMope2nY5yKXI5ja68qH5yTRDnSp5Pyyx71HXxD+TUfC0gW2Bf0zNaChMEebfEzh6T5sMGyRBKp9kiP9PnG0S1+3Bdi9854HqCyPXfMrGWPaQpTwCQ9mjeJZYg78ZE5Wo8oEd874nEvNdvLH3dw61Llfamb/14Tg1ThwXSQ9BuPWUx+y/UYqVM70GGAZyvgpqpalPv4t9s3aRKXkjwKypHKaGb7/uOR2huYCDog1bESMti617jyRp1+EhFIF8mPjo9HPJlxpMOTKPTsJS9HCmMSBOfeH7d7Jlm22ElPYETIdJAzjnHHmp6bd5FQ3pmXB39QoMVoLaqB3BM5e1gpYeh2LpClqXbto0Kf9WGmQ/lN2s0ROD9pTbGjIDlXBo0RNWu+72FLMYbW8BTqKVUqFbhCit803MZYwnsozZtqNnVQvxhAN3AgxBY1emInN4T7OXdPCFIvHMQCS+9Lb+VeUEZnzV0gKIYbT06PEVc4VV1XAkGI7hCbDPQKxXhrLeI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: opennode/waldur-freeipa
